version: '3'

services:
  api:
    build:
      context: ./lenta
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate &&
            echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_user('user', 'user@example.com', 'password')\" | python3 manage.py shell &&
            python manage.py my_commands &&
            python3 manage.py runserver 0:8000"

  db:
    image: postgres:latest
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
