# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:  
  
  
  web:
    build: lenta/
    restart: always
    ports:
     - "8000:8000"
    # "зависит от", 
    # depends_on:
    #   - db
    # env_file:
      # - ./.env 