# Generated by Django 4.1.11 on 2023-10-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='pr_sku_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='st_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='salesforecast',
            old_name='pr_sku_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesforecast',
            old_name='st_id',
            new_name='store',
        ),
    ]
