# Generated by Django 4.1.11 on 2023-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_pr_uom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pr_cat_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_group_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_sku_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_subcat_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='pr_uom_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='st_city_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='st_division_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='st_id',
            field=models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='st_is_active',
            field=models.BooleanField(db_index=True),
        ),
    ]
