# Generated by Django 4.1.11 on 2023-10-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_sales_units_salesforecast_forecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='pr_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.productgroup'),
        ),
    ]
