# Generated by Django 4.1.11 on 2023-10-11 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productcategory_pr_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='pr_cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.productcategory'),
        ),
    ]
