openapi: 3.0.3
info:
  title: API для ML сервиса команды "За еду!"
  version: 1.0.0
  description: Добавим сюда крутое описание, позже..
paths:
  /api/v1/categories/:
    get:
      operationId: api_v1_categories_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
          description: ''
  /api/v1/forecast/:
    get:
      operationId: api_v1_forecast_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesForecast'
          description: ''
    post:
      operationId: api_v1_forecast_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SalesForecast'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SalesForecast'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SalesForecast'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesForecast'
          description: ''
  /api/v1/sales/:
    get:
      operationId: api_v1_sales_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sales'
          description: ''
  /api/v1/shops/:
    get:
      operationId: api_v1_shops_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Store'
          description: ''
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Categories:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        pr_group_id:
          type: string
          maxLength: 255
        pr_cat_id:
          type: string
          maxLength: 255
        pr_subcat_id:
          type: string
          maxLength: 255
        pr_sku_id:
          type: string
          maxLength: 255
        pr_uom_id:
          type: integer
      required:
      - id
      - pr_cat_id
      - pr_group_id
      - pr_sku_id
      - pr_subcat_id
      - pr_uom_id
    Sales:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
        pr_sales_type_id:
          type: boolean
        pr_sales_in_units:
          type: integer
        pr_promo_sales_in_units:
          type: integer
        pr_sales_in_rub:
          type: number
          format: double
        pr_promo_sales_in_rub:
          type: number
          format: double
        store:
          type: integer
        product:
          type: integer
      required:
      - date
      - id
      - pr_promo_sales_in_rub
      - pr_promo_sales_in_units
      - pr_sales_in_rub
      - pr_sales_in_units
      - pr_sales_type_id
      - product
      - store
    SalesForecast:
      type: object
      properties:
        store:
          type: integer
        product:
          type: integer
        forecast_date:
          type: string
          format: date
        forecast:
          type: object
          additionalProperties: {}
      required:
      - forecast
      - forecast_date
      - product
      - store
    Store:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        st_id:
          type: string
          maxLength: 255
        st_city_id:
          type: string
          maxLength: 255
        st_division_code:
          type: string
          maxLength: 255
        st_type_format_id:
          type: integer
        st_type_loc_id:
          type: integer
        st_type_size_id:
          type: integer
        st_is_active:
          type: boolean
      required:
      - id
      - st_city_id
      - st_division_code
      - st_id
      - st_is_active
      - st_type_format_id
      - st_type_loc_id
      - st_type_size_id
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
