name: Cleanup Docker Images

on:
  workflow_run:
    workflows: ["main"]  # Замените "Name of Your Build Workflow" на имя вашего существующего workflow

jobs:
  cleanup-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Remove all Docker images
      run: |
        # Удаление всех Docker образов
        docker rmi $(docker images -q) -f
